# Generated by Django 4.2.7 on 2023-12-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contribuinte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("nif", models.CharField(blank=True, max_length=10, null=True)),
                ("morada", models.CharField(max_length=300)),
                ("municipio", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Taxa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "valor_contrato",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=models.DecimalField(decimal_places=2, max_digits=10),
                        max_digits=10,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "contribuiente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxas_pagas",
                        to="gupagamento.contribuinte",
                    ),
                ),
            ],
        ),
    ]
