# Generated by Django 4.2.7 on 2025-09-15 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gupagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuinte',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuientes_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxa',
            name='emitido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxas_emitidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
