# Generated by Django 4.2.7 on 2023-12-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gupagamento", "0002_rename_data_taxa_data_pagamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxa", old_name="contribuiente", new_name="contribuinte",
        ),
    ]
