# Generated by Django 4.2.7 on 2026-07-03 10:47

from django.db import migrations, models
import django.db.models.deletion


def copy_departments(apps, schema_editor):
    """Merge projectos.Department names into accounts.Department (by name;
    no projects reference them yet, so pks need not be preserved)."""
    OldDepartment = apps.get_model("projectos", "Department")
    NewDepartment = apps.get_model("accounts", "Department")
    for old in OldDepartment.objects.all():
        NewDepartment.objects.get_or_create(
            name=old.name, defaults={"description": old.description}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_alter_customuser_departamento'),
        ('projectos', '0001_initial'),
        ('ticket', '0004_alter_ticket_department_delete_department'),
    ]

    operations = [
        migrations.RunPython(copy_departments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.department', verbose_name='Departamento'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
