# Generated by Django 4.2.7 on 2025-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
