# Generated by Django 4.2.7 on 2024-04-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=200)),
                ("gerente", models.CharField(blank=True, max_length=250, null=True)),
                ("telefone", models.CharField(max_length=9)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("morada", models.CharField(max_length=250)),
                (
                    "provincia",
                    models.CharField(max_length=200, verbose_name="província"),
                ),
                (
                    "municipio",
                    models.CharField(max_length=200, verbose_name="município"),
                ),
                ("nif", models.CharField(blank=True, max_length=16, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "especialidade",
                    models.CharField(
                        choices=[
                            ("CT", "Construção"),
                            ("FI", "Fiscalização"),
                            ("PJ", "Projecto"),
                        ],
                        default="CT",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["nome"], name="empresas_em_nome_9b04de_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "documento",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alvara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("emissao", models.DateField()),
                ("termino", models.DateField()),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("Primeira", "Primeira"),
                            ("Segunda", "Segunda"),
                            ("Terceira", "Terceira"),
                            ("Quarta", "Quarta"),
                        ],
                        default="Quarta",
                        max_length=8,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_pagamento", models.DateField()),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alvara",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
