# Generated by Django 4.2.7 on 2023-11-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "especialidade",
                "verbose_name_plural": "categorias",
                "indexes": [
                    models.Index(fields=["nome"], name="empresas_es_nome_3b88fe_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=200)),
                ("gerente", models.CharField(max_length=250)),
                ("telefone", models.CharField(max_length=9)),
                ("email", models.EmailField(max_length=254)),
                ("morada", models.CharField(max_length=250)),
                (
                    "provincia",
                    models.CharField(max_length=200, verbose_name="província"),
                ),
                (
                    "municipio",
                    models.CharField(max_length=200, verbose_name="município"),
                ),
                ("nif", models.CharField(max_length=16)),
                (
                    "especialidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to="empresas.especialidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alvara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=200)),
                ("emissao", models.DateField()),
                ("termino", models.DateField()),
                ("tipo", models.IntegerField()),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alvara",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["nome"], name="empresas_em_nome_9b04de_idx"),
        ),
    ]
