# Generated by Django 4.2.7 on 2024-02-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="gerente",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nif",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
