# Generated by Django 4.2.7 on 2024-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_email_alter_empresa_gerente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="especialidade",
            field=models.CharField(
                choices=[
                    ("CT", "Construção"),
                    ("FI", "Fiscalização"),
                    ("PJ", "Projecto"),
                ],
                default="CT",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="Especialidade",
        ),
    ]
