# Generated by Django 4.2.7 on 2023-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_empresa_created_at_alter_empresa_gerente_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="alvara",
            name="slug",
            field=models.SlugField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
