# Generated by Django 4.2.7 on 2026-07-03 10:47

from django.db import migrations, models
import django.db.models.deletion


def copy_departments(apps, schema_editor):
    """Copy ticket.Department rows into accounts.Department keeping the same
    primary keys, so existing Ticket.department_id values remain valid."""
    OldDepartment = apps.get_model("ticket", "Department")
    NewDepartment = apps.get_model("accounts", "Department")
    for old in OldDepartment.objects.all():
        NewDepartment.objects.update_or_create(
            pk=old.pk,
            defaults={"name": old.name, "description": old.description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_alter_customuser_departamento'),
        ('ticket', '0003_alter_ticket_options_ticketcomment'),
    ]

    operations = [
        migrations.RunPython(copy_departments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_tickets', to='accounts.department', verbose_name='Departamento'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
