# Generated by Django 4.2.7 on 2023-11-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Benificiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="GPIST", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Contribuinte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("nif", models.CharField(max_length=10)),
                ("morada", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Licenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_pagamento", models.DateField()),
                ("potencia", models.FloatField(blank=True, null=True)),
                (
                    "distincao",
                    models.CharField(
                        choices=[("PT", "Pt"), ("GG", "Gg")], max_length=2
                    ),
                ),
                (
                    "benificiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas_recebidas",
                        to="taxas.benificiario",
                    ),
                ),
                (
                    "contribuinte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencas_pagas",
                        to="taxas.contribuinte",
                    ),
                ),
            ],
        ),
    ]
