# Generated by Django 4.2.7 on 2023-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribuinte",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
