# Generated by Django 4.2.7 on 2024-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0002_alter_contribuinte_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribuinte",
            name="telefone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="contribuinte",
            name="nif",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
