# Generated by Django 4.2.7 on 2024-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0003_contribuinte_telefone_alter_contribuinte_nif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribuinte",
            name="nif",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
