# Generated by Django 4.2.7 on 2024-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxas", "0004_alter_contribuinte_nif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenca",
            name="benificiario",
            field=models.CharField(default="GPIST", max_length=100),
        ),
        migrations.DeleteModel(
            name="Benificiario",
        ),
    ]
